feat: add task 181-185
valdispatriarh/codemu pull request #3
Opened 2023-09-10 20:38 UTC by valdispatriarh

2023-09-10 21:51 UTC, mikalai-hryb requested changes

2023-09-10 21:51 UTC, mikalai-hryb commented on 184.js
> +console.log(1, Math.pow(2, 10))
як яшчэ можна гэтага дамагчыся?

2023-09-10 21:51 UTC, mikalai-hryb commented on 184.js
> +console.log(2, Math.sqrt(245))
як яшчэ можна гэтага дамагчыся?

2023-09-10 21:51 UTC, mikalai-hryb commented on 184.js
> +}
ты ўжываеш `i` тут толькі каб атрымаць элемент з масіва, таму тут лепей ужываць `for of`

2023-09-10 21:51 UTC, mikalai-hryb commented on 184.js
> +console.log(3, Math.sqrt(sum184))
паспрабуй вырашыць гэту задачу з дапамогай [.reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

2023-09-10 21:51 UTC, mikalai-hryb commented on 185.js
> +obj185.floor = floor
ствары аб'ект `obj185` адразу з ключамі `ceil` і `floor`

2023-09-11 15:57 UTC, valdispatriarh commented on 184.js
> +console.log(1, Math.pow(2, 10))
console.log(1, 2**10)

2023-09-11 16:02 UTC, valdispatriarh commented on 184.js
> +console.log(2, Math.sqrt(245))
console.log(2, Math.pow(245, 1/2))
console.log(2, 245**(1/2))

2023-09-11 16:05 UTC, valdispatriarh commented on 184.js
> +}
паправіў

2023-09-11 16:36 UTC, valdispatriarh commented on 184.js
> +console.log(3, Math.sqrt(sum184))
зрабіў

2023-09-11 16:41 UTC, valdispatriarh commented on 185.js
> +obj185.floor = floor
зрабіў

2023-09-12 15:46 UTC, mikalai-hryb requested changes
добра атрымалася

калі ласка, больш не дабаўляй новых файлаў у гэты ПР, лепей ствары новы ПР

2023-09-12 15:46 UTC, mikalai-hryb commented on 187.js
> +console.log(1, getRandomValues(10, 100))
сам напісаў?
трэба ад 1 да 100, а не 10-100

2023-09-12 15:46 UTC, mikalai-hryb commented on 187.js
> +let numMax = 9007199254740991
што гэта за магічны лік?

2023-09-12 15:46 UTC, mikalai-hryb commented on 187.js
> +console.log(arr187)
гэта не аптымальнае рашэнне
у цябе 10 ітэрацый, на кожнай ітерацыі ты стварае такую ж самую`getRandomValues2` функцыю
функцыя павінна быць па за `for`

2023-09-12 15:46 UTC, mikalai-hryb commented on 188.js
> +}
лепей стварыць нешта такое 
```
const arr = [[-8, 5], [8, 99], [88, 698]]
```
і ўжываць `for..of`

калі ласка, перапішы

2023-09-12 15:52 UTC, mikalai-hryb commented on 184.js
> +console.log(3, Math.sqrt(total))
тут `for` не патрэбны
узвадзі ў трэцюю ступень адразу ў `.reduce()`

2023-09-12 15:52 UTC, mikalai-hryb commented on 184.js
> +}
ужо лепей, аставіў новы каментар

2023-09-12 15:54 UTC, mikalai-hryb commented on 184.js
> +}
усё добра
тут добра будзе глядзецца скарочаная форма

2023-09-12 15:54 UTC, mikalai-hryb commented on 184.js
> +console.log(3, Math.sqrt(sum184))
добра, заставіў новы каментар

2023-09-12 15:56 UTC, mikalai-hryb commented on 185.js
> +obj185.floor = floor
паспрабуй замяніць `undefined` адразу на патрэбнае значэнне

2023-09-12 15:56 UTC, mikalai-hryb commented on 185.js
> +obj185.floor = floor
аставіў новы каментар

2023-09-12 17:30 UTC, valdispatriarh commented
штосці я запутаўся, я учора жадаў адкрыць новы PR, але як я разумею цяпер патрэбна было зрабіць 5 заданняў не пушыць іх, потоым ачыніць PR,  і потым запушыць, так? учора пры намаганні адкрыць PR мне писала што смержа аўтаматычна калі я яго адчыню.

2023-09-20 16:04 UTC, valdispatriarh commented on 187.js
> +console.log(1, getRandomValues(10, 100))
спачатку скапіяваў прыклад с сайту, паглядзеў на return, потым выдаліў яго, запісаў  па памяці сам і так пару раз, пра console забыўся

2023-09-20 16:07 UTC, valdispatriarh commented on 187.js
> +console.log(1, getRandomValues(10, 100))
паправіў

2023-09-20 16:10 UTC, valdispatriarh commented on 187.js
> +let numMax = 9007199254740991
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

2023-09-20 16:13 UTC, valdispatriarh commented on 187.js
> +let numMax = 9007199254740991
максимальное число из Number

2023-09-20 16:23 UTC, valdispatriarh commented on 187.js
> +console.log(arr187)
зглупіў, гэта адбываецца таму што пока  у мяне не адклалася у галаве для чаго патрэбна функцыя і як Ёй карыстацца

2023-09-20 16:30 UTC, valdispatriarh commented on 187.js
> +console.log(arr187)
справіў

2023-09-20 16:43 UTC, valdispatriarh commented on 188.js
> +}
пераписаў

2023-09-20 16:48 UTC, valdispatriarh commented on 184.js
> +console.log(3, Math.sqrt(total))
Найдите квадратный корень из суммы кубов его элементов. Для решения воспользуйтесь циклом for.

2023-09-20 16:53 UTC, valdispatriarh commented on 184.js
> +}
папраіў

2023-09-20 16:58 UTC, valdispatriarh commented on 185.js
> +obj185.floor = floor
атрымалася

2023-09-21 16:43 UTC, mikalai-hryb commented on 187.js
> +let numMax = 9007199254740991
тады так і ўжывай
let  `numMax  = Number.MAX_SAFE_INTEGER` - такі запіс больш зразумелы, а працуе аднолькава

2023-09-21 16:49 UTC, mikalai-hryb commented on 184.js
> +console.log(3, Math.sqrt(total))
згодзен, тады ў цябе ўсё правільна

калі б не было пра `for`, то вось так можна было рашаць
```suggestion
let arr3b = [4, 2, 5, 19, 13, 0, 10]
let total = arr3b.reduce(function(a, b){
    return a + b**3
})
console.log(3, Math.sqrt(total))
```

2023-09-21 16:49 UTC, mikalai-hryb commented on 184.js
> +console.log(3, Math.sqrt(total))
зачыні гэтую размову, калі азнаёмішся

2023-09-21 16:52 UTC, mikalai-hryb commented on 185.js
> +obj185.floor = floor
не зусім
я хацеў пабачыць

```
let obj185 = {
    'ceil': Math.ceil(num2),
    'floor': Math.floor(num2)
}
```

замест 8 радкоў атрымалася 4

2023-09-21 16:53 UTC, mikalai-hryb commented on 185.js
> +obj185.floor = floor
выправі

2023-09-21 16:54 UTC, mikalai-hryb commented
пасля змен можаж мержыць ПР

2023-09-22 17:25 UTC, valdispatriarh commented on 187.js
> +let numMax = 9007199254740991
паправіў

2023-09-22 17:30 UTC, valdispatriarh commented on 185.js
> +obj185.floor = floor
паправіў

2023-09-22 17:31 UTC, merged