feat: add task 206-210
valdispatriarh/codemu pull request #7
Opened 2023-10-04 19:30 UTC by valdispatriarh

2023-10-05 17:20 UTC, mikalai-hryb requested changes

2023-10-05 17:20 UTC, mikalai-hryb commented on 207.js
> +//похожая ситуция со 2 заданием только вместо else обычная строчка кода, поведение точно такое же
так, правільна, што заўважыў, што паводзіны такія ж самыя

такі прыём (`return` адразу пасля `if`, але не ў `else`) дастаткова часта ўжываецца, проста таму, што менш грувасткі код

2023-10-05 17:20 UTC, mikalai-hryb commented on 209.js
> +console.log(func209(1000000))
Добра, што паспрабаваў ужываць `try/catch` і `throw`

Толькі задача рашаецца прасцей
> Пусть функция возвращает количество итераций, которое потребовалось для достижения результата.

Гэта значыць, што калі ў цябе, напрыкад, `20`, то колькасць ітэрацый будзе раўна `2`.
А калі `-2`, то колькасць ітэрацый будзе раўна `0` (табе не патрэбен тут ні  `try/catch`, ні `throw`)

2023-10-06 14:40 UTC, valdispatriarh commented on 209.js
> +console.log(func209(1000000))
паправіў

2023-10-07 13:28 UTC, mikalai-hryb commented on 209.js
> +console.log(func209(1000000))
так, ўсё добра :+1:

2023-10-07 13:31 UTC, mikalai-hryb commented
усё вырашана правільна :+1: 
вырашай канфлікт і мержы 🚀

2023-10-07 13:31 UTC, mikalai-hryb approved these changes

2023-10-08 13:10 UTC, merged